nutriwatch/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'homepage/index'

  root 'homepage#index'

  get '/form', to: 'homepage#form'
  post '/form', to: 'homepage#filter'

  get 'dishes/query', to: "dishes#query", as: :dishes_query
  resources :dishes do
    collection do
      get 'query'
    end
  end

  get 'users/signup', to: 'users#new'
  post 'users/signup',  to: 'users#create'

  get    '/filter',   to: 'homepage#new'
  post   '/filter',   to: 'homepage#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  
  resources :restaurants #Restful routes for RestaurantsController
  resources :restaurantmenus #Restful routes for RestaurantmenusController
  resources :restaurantcuisines #REST routes for RestaurantcuisinesController
  resources :ingredients #Restful routes for IngredientsController
  resources :dishes #Restful routes for DishesController
  resources :dishingredients #Restful routes for DishingredientsController
  resources :dietaryviolations #Restful routes for DietaryViolationsController 
  resources :homepage
  resources :users

end

nutriwatch/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true

  def self.search(r_id: nil, name: nil)
  	with_r_id(r_id)
  		.with_name(name)
  end

  scope :with_r_id, proc { |r_id|
  	if r_id.present?
  		where(r_id: r_id)
  	end
  }

  scope :with_name, proc { |name|
  	if name.present?
  		where(name: name)
  	end
  }
end

nutriwatch/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def show
    @restaurant = Restaurant.find params[:id]
    @restaurantdishes = Dish.select("d_id, name, price, rating, cuisine, calories").where(r_id: params[:id])

    @vegandishes = Dishingredient.find_by_sql("
      SELECT DISTINCT dishes.d_id, dishes.r_id, dishes.m_id, dishes.name, dishes.price, dishes.rating, dishes.cuisine, dishes.calories
      FROM dishes, (
        SELECT DISTINCT d_id 
        FROM dishes
        WHERE r_id = #{params[:id]}
      EXCEPT
        SELECT DISTINCT d_id 
        FROM dishingredients, (
          SELECT DISTINCT ingredient 
          FROM dietaryviolations 
          WHERE diet='Vegan') AS r1 
        WHERE r1.ingredient = dishingredients.ingredient ) AS r2
      WHERE dishes.d_id = r2.d_id
      ORDER BY dishes.d_id
                                          ")
    
    @vegetariandishes = Dishingredient.find_by_sql("
      SELECT DISTINCT dishes.d_id, dishes.r_id, dishes.m_id, dishes.name, dishes.price, dishes.rating, dishes.cuisine, dishes.calories
      FROM dishes, (
        SELECT DISTINCT d_id 
        FROM dishes
        WHERE r_id = #{params[:id]}
      EXCEPT
        SELECT DISTINCT d_id 
        FROM dishingredients, (
          SELECT DISTINCT ingredient 
          FROM dietaryviolations 
          WHERE diet='Vegetarian') AS r1 
        WHERE r1.ingredient = dishingredients.ingredient ) AS r2
      WHERE dishes.d_id = r2.d_id
      ORDER BY dishes.d_id
                                          ")

    @glutenfreedishes = Dishingredient.find_by_sql("
      SELECT DISTINCT dishes.d_id, dishes.r_id, dishes.m_id, dishes.name, dishes.price, dishes.rating, dishes.cuisine, dishes.calories
      FROM dishes, (
        SELECT DISTINCT d_id 
        FROM dishes
        WHERE r_id = #{params[:id]}
      EXCEPT
        SELECT DISTINCT d_id 
        FROM dishingredients, (
          SELECT DISTINCT ingredient 
          FROM dietaryviolations 
          WHERE diet='Gluten Free') AS r1 
        WHERE r1.ingredient = dishingredients.ingredient ) AS r2
      WHERE dishes.d_id = r2.d_id
      ORDER BY dishes.d_id
                                          ")
 
    @nutallergydishes = Dishingredient.find_by_sql("
      SELECT DISTINCT dishes.d_id, dishes.r_id, dishes.m_id, dishes.name, dishes.price, dishes.rating, dishes.cuisine, dishes.calories
      FROM dishes, (
        SELECT DISTINCT d_id 
        FROM dishes
        WHERE r_id = #{params[:id]}
      EXCEPT
        SELECT DISTINCT d_id 
        FROM dishingredients, (
          SELECT DISTINCT ingredient 
          FROM dietaryviolations 
          WHERE diet='Nut Allergy') AS r1 
        WHERE r1.ingredient = dishingredients.ingredient ) AS r2
      WHERE dishes.d_id = r2.d_id
      ORDER BY dishes.d_id
                                          ")
  end

  def destroy
    begin
      @restaurant = Restaurant.find params[:id]
      @restaurant.destroy
      redirect_to restaurants_path
    rescue ActiveRecord::ActiveRecordError
      flash[:danger] = "You do not have the proper permissions to do this action!"
      redirect_to homepage_index_path
    end 
  end

  def update
    @restaurant = Restaurant.find params[:id]

    
    begin
    if @restaurant.update restaurant_params
      flash[:success] = "Updated Restaurant!"
      redirect_to restaurants_path
    else
      render :edit
    end
    rescue ActiveRecord::ActiveRecordError
      flash[:danger] = "You have entered invalid parameters. Unable to update."
      redirect_to restaurants_path
    end
  end

  def create
    @restaurant = Restaurant.new restaurant_params
    


    begin
    if @restaurant.save
      flash[:success] = "Added Your Restaurant!"
      redirect_to restaurants_path
    else
      render :new
    end
    rescue ActiveRecord::ActiveRecordError
      flash[:danger] = "Overlapping parameters! You are not allowed to do that."
      redirect_to restaurants_path
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:r_id, :name)
  end
end

nutriwatch/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

nutriwatch/app/views/restaurants/_form.html.erb
<h3>Restaurants</h3>

<% if @restaurant.errors.any? %>
  <div class ="errors">
    <% @restaurant.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>
<% end %>

<%# [START restaurant_form] %>
<%= form_for @restaurant do |f| %>
  <div class="form-group">
    <%= f.label :r_id %>
    <%= f.text_field :r_id %>
  </div>
  <div class="form-group">
    <%= f.label :name, "Restaurant Name" %>
    <%= f.text_field :name %>
  </div>

  <button class="btn btn-success" type="submit">Save Data</button>
<% end %>
<%# [END restaurant_form] %>

nutriwatch/app/views/restaurants/index.html.erb
<h1 style="color:white">Restaurants List</h1>

<div class="modal fade" id="newRestaurantModal" tabindex="-1" role="dialog" aria-labelledby="newRestaurantLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      Testing
    </div>
  </div>
</div>

<a href="<%= new_restaurant_path %>" class="btn btn-success btn-sm" data-toggle="modal" data-target="#newRestaurantModal">
  <i class="glyphicon glyphicon-plus"></i>
  <span>Add New Restaurant</span>
</a>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <section>
      <div class="tbl-header">
        <table cellpadding="0" cellspacing="0" border="0">
          <thead>
            <tr>
              <th>Restaurant Name</th>
            </tr>
          </thead>
        </table>
      </div>

      <div class="tbl-content">
        <table cellpadding="0" cellspacing="0" border="0">
          <tbody>
            <% @restaurants.each do |restaurant| %>
            <tr align="left">
              <td>
                <%= link_to restaurant_path(restaurant) do %>
                  <%= restaurant.name %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </section>
  </div>
</div>

nutriwatch/app/views/restaurants/new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title" id="newRestaurantLabel">Add New Restaurant</h4>
</div>

<div class="modal-body">
  <%= render partial: "form" %>
</div>

nutriwatch/app/views/restaurants/show.html.erb
<% @restaurantdishes.each do |dish| %> 
  <div class="modal fade" id="dishModal<%= dish.d_id %>" tabindex="-1" role="dialog" aria-labelledby="dish<%= dish.d_id %>Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
<% end %>

<div class="modal fade" id="newDishModal" tabindex="-1" role="dialog" aria-labelledby="newDishLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="container-fluid">
  
  <h1 style="color:white"><%= @restaurant.name %> Info</h1>
  
  <div class="row">
    <div class="col-sm-offset-2">
      <div class="btn-group" style="padding-top:50px">
        <a href="<%= new_dish_path %>" class="btn btn-success btn-sm" data-toggle="modal" data-target="#newDishModal">
          <i class="glyphicon glyphicon-plus"></i>
          <span>Add New Dish</span>
        </a>
        
        <%= link_to edit_restaurant_path(@restaurant), class: "btn btn-primary btn-sm" do %>
          <i class="glyphicon glyphicon-edit"></i>
          <span>Edit Restaurant</span>
        <% end %>
        <%= link_to restaurant_path(@restaurant), class: "btn btn-danger btn-sm", method: :delete do %>
          <i class="glyphicon glyphicon-trash"></i>
          <span>Delete Restaurant</span>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Diet Modal Buttons -->
  <div class="row" style="padding-top:20px">

    <div class="col-sm-2 col-sm-offset-2">
      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#veganFilterModal">
        Vegan Options
      </button>
    </div>

    <div class="col-sm-2">
      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#vegetarianFilterModal">
        Vegetarian Options
      </button>
    </div>

    <div class="col-sm-2">
      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#glutenFreeFilterModal">
        Gluten Free Options
      </button>
    </div>

    <div class="col-sm-2">
      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#nutAllergyFilterModal">
        Nut Free Options
      </button>
    </div>

  </div>

  <div class="row">
    <div class="col-sm-offset-1">

      <section>
        <div class="tbl-header">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th>Dish Name</th>
                <th>Price</th>
                <th>Rating</th>
                <th>Cuisine</th>
                <th>Calories</th>
                <th>Delete/Edit</th>
              </tr>
            </thead>
          </table>
        </div>

        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
              <% @restaurantdishes.each do |dish| %>
                <tr align="left">
                  <td><%= dish.name %></td>
                  <td><%= dish.price %></td>
                  <td><%= dish.rating %></td>
                  <td><%= dish.cuisine %></td>
                  <td><%= dish.calories %></td>
                  <td>
                    <div class="btn-group">
                      <a href="<%= edit_dish_path(dish.d_id) %>" class="btn btn-info btn-sm" data-toggle="modal" data-target="#dishModal<%= dish.d_id %>">
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>Edit Dish</span>
                      </a>

                      <%= link_to dish_path(dish.d_id), class: "btn btn-danger btn-sm", method: :delete do %>
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Delete Dish</span>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

      </section>


    </div>
  </div>






  <div class="modal fade" id="veganFilterModal" tabindex="-1" role="dialog" aria-labelledby="veganFilterLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content" style="background-color:#22384f">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="veganFilterLabel" style="color:white">Vegan Dishes</h4>
        </div>

        <div class="modal-body">
            <!-- Vegan Dishes -->
          <div class="row">
            <div class="col-sm-offset-1">
              <section>
                <div class="tbl-header">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <thead>
                      <tr>
                        <th>Dish Name</th>
                        <th>Price</th>
                        <th>Rating</th>
                        <th>Cuisine</th>
                        <th>Calories</th>
                      </tr>
                    </thead>
                  </table>
                </div>

                <div class="tbl-content">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                      <% @vegandishes.each do |dish| %>
                        <tr align="left">
                          <td><%= dish.name %></td>
                          <td><%= dish.price %></td>
                          <td><%= dish.rating %></td>
                          <td><%= dish.cuisine %></td>
                          <td><%= dish.calories %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="modal fade" id="vegetarianFilterModal" tabindex="-1" role="dialog" aria-labelledby="vegetarianFilterLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content" style="background-color:#22384f">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="vegetarianFilterLabel" style="color:white">Vegetarian Dishes</h4>
        </div>

        <div class="modal-body">
            <!-- Vegetarian Dishes -->
          <div class="row">
            <div class="col-sm-offset-1">
              <section>
                <div class="tbl-header">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <thead>
                      <tr>
                        <th>Dish Name</th>
                        <th>Price</th>
                        <th>Rating</th>
                        <th>Cuisine</th>
                        <th>Calories</th>
                      </tr>
                    </thead>
                  </table>
                </div>

                <div class="tbl-content">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                      <% @vegetariandishes.each do |dish| %>
                        <tr align="left">
                          <td><%= dish.name %></td>
                          <td><%= dish.price %></td>
                          <td><%= dish.rating %></td>
                          <td><%= dish.cuisine %></td>
                          <td><%= dish.calories %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="glutenFreeFilterModal" tabindex="-1" role="dialog" aria-labelledby="glutenFreeFilterLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content" style="background-color:#22384f">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="glutenFreeFilterLabel" style="color:white">Gluten Free Dishes</h4>
        </div>

        <div class="modal-body">
            <!-- Gluten Free Dishes -->
          <div class="row">
            <div class="col-sm-offset-1">
              <section>
                <div class="tbl-header">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <thead>
                      <tr>
                        <th>Dish Name</th>
                        <th>Price</th>
                        <th>Rating</th>
                        <th>Cuisine</th>
                        <th>Calories</th>
                      </tr>
                    </thead>
                  </table>
                </div>

                <div class="tbl-content">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                      <% @glutenfreedishes.each do |dish| %>
                        <tr align="left">
                          <td><%= dish.name %></td>
                          <td><%= dish.price %></td>
                          <td><%= dish.rating %></td>
                          <td><%= dish.cuisine %></td>
                          <td><%= dish.calories %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="nutAllergyFilterModal" tabindex="-1" role="dialog" aria-labelledby="nutAllergyFilterLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content" style="background-color:#22384f">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="nutAllergyFilterLabel" style="color:white">Nut Free Dishes</h4>
        </div>

        <div class="modal-body">
          <!-- Nut Allergy Dishes -->
          <div class="row">
            <div class="col-sm-offset-1">
              <section>
                <div class="tbl-header">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <thead>
                      <tr>
                        <th>Dish Name</th>
                        <th>Price</th>
                        <th>Rating</th>
                        <th>Cuisine</th>
                        <th>Calories</th>
                      </tr>
                    </thead>
                  </table>
                </div>

                <div class="tbl-content">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                      <% @nutallergydishes.each do |dish| %>
                        <tr align="left">
                          <td><%= dish.name %></td>
                          <td><%= dish.price %></td>
                          <td><%= dish.rating %></td>
                          <td><%= dish.cuisine %></td>
                          <td><%= dish.calories %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>


<script>
$(window).on("load resize ", function() {
  var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
  $('.tbl-header').css({'padding-right':scrollWidth});
}).resize();
</script>