nutriwatch/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'homepage/index'

  root 'homepage#index'

  get '/form', to: 'homepage#form'
  post '/form', to: 'homepage#filter'

  get 'dishes/query', to: "dishes#query", as: :dishes_query
  resources :dishes do
    collection do
      get 'query'
    end
  end

  get 'users/signup', to: 'users#new'
  post 'users/signup',  to: 'users#create'

  get    '/filter',   to: 'homepage#new'
  post   '/filter',   to: 'homepage#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  
  resources :restaurants #Restful routes for RestaurantsController
  resources :restaurantmenus #Restful routes for RestaurantmenusController
  resources :restaurantcuisines #REST routes for RestaurantcuisinesController
  resources :ingredients #Restful routes for IngredientsController
  resources :dishes #Restful routes for DishesController
  resources :dishingredients #Restful routes for DishingredientsController
  resources :dietaryviolations #Restful routes for DietaryViolationsController 
  resources :homepage
  resources :users

end

nutriwatch/app/models/homepage.rb
class Homepage < ActiveRecord::Base

	has_and_belongs_to_many :restaurantcuisine
	has_and_belongs_to_many :dietaryviolation

	before_save { self.d_name = d_name.downcase } if ':d_name.present?'
	before_save { self.r_name = r_name.downcase } if ':r_name.present?'

	validates :c_max, numericality: { only_integer: true, less_than_or_equal_to: 5000, greater_than_or_equal_to: :c_min }
	validates :c_min, numericality: { only_integer: true, less_than_or_equal_to: :c_max, greater_than_or_equal_to: 0 }

	validates :r_max, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: :r_min }
	validates :r_min, numericality: { only_integer: true, less_than_or_equal_to: :r_max, greater_than_or_equal_to: 0 }

	validates :p_max, numericality: { only_integer: true, less_than_or_equal_to: 50, greater_than_or_equal_to: :p_min }
	validates :p_min, numericality: { only_integer: true, less_than_or_equal_to: :p_max, greater_than_or_equal_to: 0 }

    validates_associated :restaurantecuisine
    validates_associated :dietaryviolation



end

nutriwatch/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
    @homepage = Homepage.new
  end

  def new
		@homepage = Homepage.new
  end

  def destroy
    @homepage = homepage.find params[:id]
    @homepage.destroy
    redirect_to homepage_path
  end

  def create
    @homepage = Homepage.new(homepage_params)
    
    if @homepage.save

      @dish_name = params[:d_name]
      @restaurant_name = params[:r_name]
      @cuisines = params[:restaurantcuisine_ids] #array
      @dietviolations = params[:dietaryviolation_ids] #array
      @calorie_min = params[:c_min]
      @calorie_max = params[:c_max]
      @rating_min = params[:r_min]
      @rating_max = params[:r_max]
      @price_min = params[:p_min]
      @price_max = params[:p_min]

      @query = @calorie_min << " <= calories <= " << @calorie_max
      @query << @rating_min << " <= rating <= " << @rating_max
      @query << @price_min << " <= price <= " << @price_max

      if !@dish_name.blank?
        @query << " AND "
        @query << "name = '" << @dish_name <<"'"
      end

      if !@restaurant_name.blank?
        @query << " AND "
        @query << "name = '" << @restaurant_name << "'"
      end

      @dishes = Dish.where(@query).reload

      @dishes.each do |dsh|
        @cuisines.each do |cuisine|
          if dsh.cuisine == cuisine
            @dishes.delete(dsh)
          end
        end
      end

      redirect_to dishes_index(@dishes), alert: "Yayyy!"
    else
      render :edit
    end
  end

  def edit
    @homepage = Homepage.find params[:id]
  end

  def show
    @homepage = Homepage.find params[:id]    
  end

  def form
    @homepage = Homepage.new
    @restaurantcuisines = Restaurantcuisine.select(:cuisine).distinct
    @dietaryviolations = Dietaryviolation.select(:diet).distinct
  	

    # @dishes = Dish.new
    # @results = params[:filter]

  #   if params[:colors]
  # user = current_user
  # user.color_ids = params[:colors]
  # user.save
  end

  def filter
    @homepage = Homepage.new(homepage_params)
  	flash[:success] = "yay you did it"
    @dish_name = params[:d_name]
    @restaurant_name = params[:r_name]
    @cuisines = params[:restaurantcuisine_ids] #array
    @dietviolations = params[:dietaryviolation_ids] #array
    @calorie_min = params[:c_min]
    @calorie_max = params[:c_max]
    @rating_min = params[:r_min]
    @rating_max = params[:r_max]
    @price_min = params[:p_min]
    @price_max = params[:p_min]

    @query = @calorie_min << " <= calories <= " << @calorie_max
    @query << @rating_min << " <= rating <= " << @rating_max
    @query << @price_min << " <= price <= " << @price_max

    if !@dish_name.blank?
      @query << " AND "
      @query << "name = '" << @dish_name <<"'"
    end

    if !@restaurant_name.blank?
      @query << " AND "
      @query << "name = '" << @restaurant_name << "'"
    end

    @dishes = Dish.where(@query).reload

    @dishes.each do |dsh|
      @cuisines.each do |cuisine|
        if dsh.cuisine == cuisine
          @dishes.delete(dsh)
        end
      end
    end

    redirect_to dishes_index(@dishes), alert: "Yayyy!"
  end


  private

  def homepage_params
    params.permit(:d_name, :r_name, :c_min, :c_max, :r_min, :r_max, :p_min, :p_max, { :restaurantcuisine_ids => [] }, { :dietaryviolation_ids => [] } )

  end

end

nutriwatch/app/helpers/homepage_helper.rb
module HomepageHelper
end

nutriwatch/app/views/homepage/_form.html.erb
<% provide(:title, 'Filters') %>
<h1>Filters</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@homepage, url: filter_path) do |f| %>

      <%= f.label "Dish Name"%>
      <%= f.text_field :d_name, class: 'form-control' %>

      <%= f.label "Restaurant" %>
      <%= f.email_field :r_name, class: 'form-control' %>

      <%= f.label "Restaurant Cuisine" %>
        <%= f.collection_check_boxes(:restaurantcuisine_ids, Restaurantcuisine.all, :cuisine, :cuisine) do |b| %>
        <%= b.label class:"label-checkbox" do%>
        <%=b.check_box + b.text%>
        <%end%>
    <% end %>

    <%= f.label "Dietary Violation" %>
        <%= f.collection_check_boxes(:dietaryviolation_ids, Dietaryviolation.all, :diet, :diet) do |b| %>
        <%= b.label class:"label-checkbox" do%>
        <%=b.check_box + b.text%>
        <%end%>
    <% end %>

   <%= f.label "Calories"%>
        <%= form_for :homepage,  url: form_path do |cal| %>   
          <div id="calorie_slider"></div>
        <%= cal.hidden_field :c_min, class: 'form-control' %>
        <%= cal.hidden_field :c_max, class: 'form-control' %>
    <% end %>

    <%= f.label "Rating"%>
        <%= form_for :homepage,  url: form_path do |rate| %>
          <div id="rating_slider"></div>
        <%= rate.hidden_field :r_min, class: 'form-control' %>
        <%= rate.hidden_field :r_max, class: 'form-control' %>
    <% end %>

    <%= f.label "Price Range"%>
        <%= form_for :homepage,  url: form_path do |price| %>
          <div id="price_slider"></div>
        <%= price.hidden_field :p_min, class: 'form-control' %>
        <%= price.hidden_field :p_max, class: 'form-control' %>
    <% end %>

  	<%= f.submit "Filter my shiz!", class: "btn btn-primary" %>
  	<%= button_to 'Filter my shiz', method: :put, d_name: 'homepage[d_name]' %>
	<%= link_to 'submit', :onclick => "$('filter_post_path').submit()" %>
	<%= submit_tag 'eff u too' %>
        
    <% end %>

  </div>
</div>

nutriwatch/app/views/homepage/edit.html.erb
<%= render partial: "form" %>

nutriwatch/app/views/homepage/form.html.erb
<head>
	<style>
	.check {
		opacity:0.5;
		color:black;
	}
	</style>
	
	<script type="text/javascript">
	$(function(){
		$(".img-check").click(function(){
			$(this).toggleClass("check");
		});
	})
	</script>
</head>

<h1 style="color:white">
	Filters
</h1>

<form class="form-horizontal">

	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
					<!-- Indicators -->
					<ol class="carousel-indicators">
						<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
						<li data-target="#carousel-example-generic" data-slide-to="1"></li>
					</ol>

					<!-- Wrapper for slides -->
					<div class="carousel-inner" role="listbox">
						<div class="item active">
							<img src="assets/dishesfilter.jpg" alt="Loop1">
							<div class="carousel-caption" style="color:white; padding-bottom:300px">
								<div class="form-group"> <!-- Dish Name -->
									<label for="full_dish_id requiredField" class="control-label">Dish Name</label>
									<input type="text" class="form-control w3-text-blue" id="full_dish_id" name="full_dish" placeholder="Dish Name">
								</div>
							</div>
						</div>

						<div class="item">
							<img src="assets/restaurantsfilter.jpg" alt="Loop2">
							<div class="carousel-caption" style="color:white; padding-bottom:300px">
								<div class="form-group"> <!-- Restaurant Name -->
									<label for="full_restaurant_id requiredField" class="control-label">Restaurant</label>
									<input type="text" class="form-control w3-text-blue" id="full_restaurant_id" name="full_restaurant" placeholder="Restaurant Name">
								</div>
							</div>
						</div>
					</div>

					<!-- Controls -->
					<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
		</div>

<!-- 		<div class="row">
			<div class="form-group">
				<label for="full_dish_id requiredField" class="control-label col-sm-2" style="color:white">Dish Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control w3-text-blue" id="full_dish_id" name="full_dish" placeholder="Dish Name">
				</div>  
			</div>
		</div>

		<div class="row">
			<div class="form-group"> 
				<label for="full_restaurant_id requiredField" class="control-label col-sm-2" style="color:white">Restaurant</label>
				<div class="col-sm-8">
					<input type="text" class="form-control w3-text-blue" id="full_restaurant_id" name="full_restaurant" placeholder="Restaurant Name">
				</div>  
			</div>
		</div> -->

		<div class="row">
			<label class="control-label col-sm-offset-2" style="color:white; font-size:20px">Cuisine</label>
			<div class="form-group">

				<% @restaurantcuisines.each do |restaurantcuisine| %>
				<div class="col-sm-4" style="color:white"><label class="btn btn-primary"><img src="assets/<%= restaurantcuisine.cuisine %>FilterImage.jpg" alt="<%= restaurantcuisine.cuisine %>pic" class="img-thumbnail img-check"><input type="checkbox" name="<%= restaurantcuisine.cuisine %>choice" id="item4" value="<%= restaurantcuisine.cuisine %>" class="hidden" autocomplete="off"></label><p style="font-size:12px"><%= restaurantcuisine.cuisine %></p></div>
				<% end %>
			</div>	
		</div>

<!-- 		<div class="row">
			<div class="form-group">
				<label class="control-label col-sm-2" style="color:white">Cuisine</label>
				
				<div class="col-sm-8">
					<% @restaurantcuisines.each do |restaurantcuisine| %>
						<div class="row">
							<div class="checkbox">
								<label>
									<input type="checkbox" name="cuisine_choices" value="<%= restaurantcuisine.cuisine %>">
                  <div style="color:white"><%= restaurantcuisine.cuisine %></div>
								</label>
							</div>
						</div>
					<% end %>
				</div>

			</div>
		</div> -->

		<div class="row">
			<div class="form-group">
				<label class="control-label col-sm-2" style="color:white">Dietary Restriction</label>

				<div class="col-sm-8">
					<% @dietaryviolations.each do |dietaryviolation| %>
					<div class="row">
						<div class="checkbox">
							<label>
								<input type="checkbox" name="diet_choices" value="<%= dietaryviolation.diet %>">
								<div style="color:white"><%= dietaryviolation.diet %></div>
							</label>
						</div>
					</div>
					<% end %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group">
				<label class="control-label col-sm-2" style="color:white">Calories</label>

				<div class="col-sm-8">
					<b style="color:white">0</b> <input id="calories_slider" type="text" class="span_calories" value="" data-slider-min="0" data-slider-max="5000" data-slider-step="25" data-slider-value="[0,1500]"/> <b style="color:white">5000</b>
					<script>
					$("#calories_slider").slider({});
					</script>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group">
				<label class="control-label col-sm-2" style="color:white">Rating</label>

				<div class="col-sm-8">
					<b style="color:white">0</b> <input id="rating_slider" type="text" class="span_rating" value="" data-slider-min="0" data-slider-max="5" data-slider-step="0.5" data-slider-value="[0,5]"/> <b style="color:white">5</b>
					<script>
					$("#rating_slider").slider({});
					</script>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group">
				<label class="control-label col-sm-2" style="color:white">Price Range</label>

				<div class="col-sm-8">
					<b style="color:white">0</b> <input id="price_slider" type="text" class="span_price" value="" data-slider-min="0" data-slider-max="50" data-slider-step="0.5" data-slider-value="[0,25]"/> <b style="color:white">50</b>
					<script>
					$("#price_slider").slider({});
					</script>
				</div>
			</div>
		</div>
	</div>						

	<div class="form-group"> <!-- Submit Button -->
		<div class="col-sm-10 col-sm-offset-2">
			<a href="<%= dishes_query_path %>"><button type="submit" class="btn btn-primary">Get Updates!</button></a>               
		</div>
	</div>        
	
</div>

</form>  

nutriwatch/app/views/homepage/index.html.erb
<!-- <div class="center jumbotron">
  <h1>Welcome to the Nutriwatch (still iffy about the name tbh)</h1>
  <h2>
    This is the home page for all your dietary needs~
  </h2>

  <%= link_to "Sign up now!", users_signup_path, class: "btn btn-lg btn-primary" %>
</div> -->

<!DOCTYPE html>
<html>
<title>Nutriwatch</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css"> -->
<body>

<!-- Header -->
<header class="w3-display-container w3-content" style="max-width:100%">
  <img class="w3-image" src="/assets/homerestaurant.jpg" alt="Me" width="100%" height="600">
  <div class="w3-display-middle">
    <div class="w3-padding-xlarge w3-border w3-border-black w3-wide w3-text-black w3-center">
      <h1 class="w3-hide-medium w3-hide-small w3-xxxlarge">NUTRIWATCH</h1>
      <h5 class="w3-hide-large" style="white-space:nowrap">NUTRIWATCH</h5>
      <h3 class="w3-hide-medium w3-hide-small">A Food App</h3>
    </div>

    <ul class="w3-navbar w3-light-grey w3-round w3-hide-small w3-display-bottommiddle w3-border w3-border-black" style="bottom:-45px">

      <li><a href="/form">Filters</a></li>
      <li><a href="<%= restaurants_path %>">Restaurants</a></li>

    </ul>
  </div>
</header>

<!-- Page content -->
<div class="w3-content w3-padding-xlarge w3-margin-top" id="portfolio">

  <!-- Images (Portfolio) -->
  <a href="<%= restaurant_path(1) %>">
    <img src="<%= asset_path('pitchforks.jpg') %>" alt="pitchforks" class="w3-image" width="1000" height="500x">
	</a>

  <a href="<%= restaurant_path(2) %>">
    <img src="<%= asset_path('loop.jpg') %>" alt="loop" class="w3-image w3-margin-top" width="1000" height="500x">
	</a>

<!-- End page <center></center>ontent -->
</div>

</body>
</html>

nutriwatch/app/views/homepage/new.html.erb
<%= render partial: "form" %>

nutriwatch/app/views/homepage/show.html.erb
<h3>Homepage stuff</h3>

<div class="btn-group">
  <%= link_to edit_homepage_path(@homepage), class: "btn btn-primary btn-sm" do %>
    <i class="glyphicon glyphicon-edit"></i>
    <span>Filter</span>
  <% end %>
</div>