nutriwatch/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'homepage/index'

  root 'homepage#index'

  get '/form', to: 'homepage#form'
  post '/form', to: 'homepage#filter'

  get 'dishes/query', to: "dishes#query", as: :dishes_query
  resources :dishes do
    collection do
      get 'query'
    end
  end

  get 'users/signup', to: 'users#new'
  post 'users/signup',  to: 'users#create'

  get    '/filter',   to: 'homepage#new'
  post   '/filter',   to: 'homepage#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  
  resources :restaurants #Restful routes for RestaurantsController
  resources :restaurantmenus #Restful routes for RestaurantmenusController
  resources :restaurantcuisines #REST routes for RestaurantcuisinesController
  resources :ingredients #Restful routes for IngredientsController
  resources :dishes #Restful routes for DishesController
  resources :dishingredients #Restful routes for DishingredientsController
  resources :dietaryviolations #Restful routes for DietaryViolationsController 
  resources :homepage
  resources :users

end

nutriwatch/app/models/dishingredient.rb
class Dishingredient < ActiveRecord::Base
end

nutriwatch/app/controllers/dishingredients_controller.rb
class DishingredientsController < ApplicationController
  PER_PAGE = 20

  def index
    page_number = params[:page] ? params[:page].to_i : 1
    dishingredient_offset = PER_PAGE * (page_number - 1)
    @dishingredients = Dishingredient.limit(PER_PAGE).offset(dishingredient_offset)
    @next_page = page_number + 1 if @dishingredients.count == PER_PAGE
  end

end

nutriwatch/app/helpers/dishingredients_helper.rb
module DishingredientsHelper
end

nutriwatch/app/views/dishingredients/index.html.erb
<h1>This page is for Dish Ingredients</h1>

<table style="width:50%">
  <tr align="left">
    <th>D_ID</th>
    <th>Ingredient</th>
  </tr>

  <% @dishingredients.each do |dishingredient| %>
    <tr align="left">
      <td><%= dishingredient.d_id %></td>
      <td><%= dishingredient.ingredient %></td>
    </tr>
  <% end %>
</table>

<% if @next_page %>
  <nav>
    <ul class="pager">
      <li><%= link_to "More", dishingredients_path(page: @next_page) %></li>
    </ul>
  </nav>
<% end %>